export interface SpacingProps {
  m?: boolean | number;
  mAuto?: boolean;
  mBottom?: boolean | number;
  mBottomAuto?: boolean;
  mBottomTight?: boolean;
  mBottomWide?: boolean;
  mLeft?: boolean | number;
  mLeftAuto?: boolean;
  mLeftTight?: boolean;
  mLeftWide?: boolean;
  mRight?: boolean | number;
  mRightAuto?: boolean;
  mRightTight?: boolean;
  mRightWide?: boolean;
  mTight?: boolean;
  mTop?: boolean | number;
  mTopAuto?: boolean;
  mTopTight?: boolean;
  mTopWide?: boolean;
  mWide?: boolean;
  p?: boolean | number;
  pBottom?: boolean | number;
  pBottomTight?: boolean;
  pBottomWide?: boolean;
  pLeft?: boolean | number;
  pLeftTight?: boolean;
  pLeftWide?: boolean;
  pRight?: boolean | number;
  pRightTight?: boolean;
  pRightWide?: boolean;
  pTight?: boolean;
  pTop?: boolean | number;
  pTopTight?: boolean;
  pTopWide?: boolean;
  pWide?: boolean;
}
